### ISSUE TITLE
Resultado trecho 

### ISSUE THREAD

**Issue by doidloko** [vagalume/API#10]
Olá, estou usando a api em um aplicativo, gostei de vários pontos dela, porém tem coisas meio obvias que o resultado não retorna, por exemplo "alô" musica conhecida do chitãozinho entre outra musicas brasileiras, há alguma chance de aumentar o resultado? onde limit = 10 ?

e tem como adicionar um extra? tipo se usuário quiser procurar por uma palavra que tenha no nome da musica e não na letra, exemplo "Só os loucos sabem" , se usuário procurar loucos aparece musica com essa palavra e não somente se esta palavra estiver na letra.

Extra : Nome Musica

e se possivel adicionar opção pra verificar musicas brasileiras ou não no get ou post
br=false or true   se usuário quiser procurar palavra "alô" em musicas brasileiras fica mais fácil de encontrar.

Obrigado.
Meu email é doidloko@gmail.com  qualquer atualização me mandem por favor agradeço.

**Comment by thadeudepaula** [comment]
No decorrer do tempo, desde a abertura deste chamado até agora, nossa api passou por diversas melhorias. Se esta solicitação ainda for justificável, por favor envie-nos um novo chamado com o exemplo da URL usada na consulta, de modo que possamos avaliar a melhor maneira de resolver.

Obrigado.
