### ISSUE TITLE
URL de letra inválida

### ISSUE THREAD

**Issue by sedir** [vagalume/API#11]
Boa tarde, tenho verificado que a API de vocês não está enviando a resposta corretamente. Observem o exemplo abaixo:

[GET] http://api.vagalume.com.br/search.php?art=titas&mus=os%20cegos%20do%20castelo&nolyrics=1

```javascript
{
   "type":"exact",
   "art":{
      "id":"3ade68b5g08b7eda3",
      "name":"Tit\u00e3s",
      "url":"http:\/\/www.vagalume.com.br\/titas\/"
   },
   "mus":[
      {
         "id":"3ade68b6g11c2fda3",
         "name":"Os Cegos do Castelo",
         "url":"http:\/\/www.vagalume.com.br",
         "lang":1
      }
   ],
   "badwords":false
}
```
Notem que o campo "mus[0]/url" mostra o link para a página principal do Vagalume, e não para a página da letra da música.

**Comment by thadeudepaula** [comment]
Obrigado @sedir, já estamos averiguando o problema.

**Comment by thadeudepaula** [comment]
Problema resolvido, obrigado por informar.
