### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by juniorppp** [vagalume/API#12]
Bom dia gostaria de saber como faço para obter o json que vcs usam para o autocomplete do site de vocês, pois queria usar a api de vocês de uma forma mais dinamica, ao procurar no meu site por uma banda, iria ler o json que vocês usam para o autocomplete e mandaria o usuario para o site de vocês, numa pagina correta.

**Comment by AmarildoLima93** [comment]
Você gostaria de buscar apenas por bandas?

**Comment by juniorppp** [comment]
Sim Amarildo gostaria apenas a lista de de bandas para fazer o autocomplete no meu site assim o usuario selecionando a banda iria para o site do vagalume. Como eles já usam um autocomplete no site deles, gostaria de obter o msm json

**Comment by AmarildoLima93** [comment]
Então junior, você pode usar a requisição "http://api.vagalume.com.br/search.art?q=Skank&limit=10"

**Comment by juniorppp** [comment]
Isso msm que precisava Amarildo, muito obrigado pela sua ajuda

**Comment by AmarildoLima93** [comment]
Nada ;). Só não esqueça de dar uma olhada nos termos de uso da Vagalume por favor. http://api.vagalume.com.br/terms/

**Comment by thadeudepaula** [comment]
ops
