### ISSUE TITLE
Não consigo fazer buscas com retornos maiores que 10 ítens

### ISSUE THREAD

**Issue by andreluisce** [vagalume/API#14]
Por mais que eu coloque o parametro limit=100 (por exemplo) o máximo de retorno é 10 itens.

**Comment by thadeudepaula** [comment]
Pode por favor enviar uma url completa de sua consulta para que possamos prosseguir com os testes?

**Comment by andreluisce** [comment]
http://api.vagalume.com.br/search.excerpt?q=hillsong&limit=100

**Comment by thadeudepaula** [comment]
@andreluisce, vamos verificar este problema e assim que tivermos uma posição publicamos aqui.

Obrigado!

**Comment by andreluisce** [comment]
@thadeudepaula  Obrigado pela rapidez e disponibilidade! 

:)

**Comment by thadeudepaula** [comment]
@andreluisce, conforme a documentação, colocamos um limite máximo de dez resultados conforme o documento de março/2014 em http://api.vagalume.com.br/docs/search/#mus.

No caso da sua consulta, search.excerpt é usado para busca por trecho. Assim sendo, já trazemos as músicas mais populares ou buscadas com a para a sua pesquisa. Quanto mais palavras você souber da música, mais específico será o resultado e independente da popularidade da música.

Como você pesquisou por "hillsong", houveram 783 resultados dos quais foram exibidos os dez melhores. Nos limitamos a retornar somente estes resultados por questões de performance. Observe que este é um padrão semelhante a motores de busca como Google ou Bing que, embora digam ter encontrado milhares de resultados, se limitam a exibir um número reduzido de paginações.

**Comment by andreluisce** [comment]
Entendi. 
A API me dá a opção de buscar os resultados das próximas páginas?

**Comment by thadeudepaula** [comment]
Não, no caso de nossa api, não há implementação de paginação.

Sugerimos que você permita ao usuário ou sistema obter resultados mais precisos tornando a pesquisa mais específica -- adicionando mais palavras à pesquisa ou substituindo as palavras por palavras mais relevantes.

**Comment by andreluisce** [comment]
Ok. Obrigado!
