### ISSUE TITLE
API Musica

### ISSUE THREAD

**Issue by AbrantesMar** [vagalume/API#3]
estou com um pequeno problema na captura do link id do youtube em sua api... pois não estou identificando o próprio..
até o exemplo que tem nela uma musica do U2, não tem o id do vídeo mas ela tem na documentação. onde está na realidade o id do vídeo.

Deis de já agradeço..

Márcio Abrantes
Desenvolvedor Mobile

**Comment by thadeudepaula** [comment]
Não conseguimos reproduzir o problema, pedimos que, caso persista, nos envie detalhes da url usada para consulta.
